#pragma once

#define DSHOT_BIT_WIDTHS 16
#define DSHOT_DMA_BUFFER_SIZE	 (DSHOT_BIT_WIDTHS+DSHOT_FRAME_SILENT_SYNC_BITS)
#define DSHOT_SPEED_KHZ			600
#define DSHOT_FRAME_SILENT_SYNC_BITS	4
#define DSHOT_TELEMETRY_BAUD		115200
#define DSHOT_CHANNELS			2
#define DSHOT_TELEMETRY_TIMEOUT_MS	3
